import logging
import secrets
from contextlib import asynccontextmanager
from uuid import uuid4

import httpx
from fastapi import FastAPI, Request, Response
from fastapi.responses import HTMLResponse, JSONResponse
from pydantic import BaseModel, ConfigDict, Field

from gateway.challenges.generator import create_challenge
from gateway.challenges.page import CLIENT_SCRIPT, challenge_page
from gateway.challenges.store import InMemoryChallengeStore
from gateway.challenges.verifier import verify_challenge
from gateway.config import Settings
from gateway.logging.events import record_decision
from gateway.policies.evaluator import Decision, evaluate_request
from gateway.proxy.origin_proxy import proxy_request
from gateway.sessions.store import InMemorySessionStore
from gateway.sessions.tokens import create_access_token

logging.basicConfig(level=logging.INFO)
LIFETIME = 300
PRIVATE_HEADERS = {"Cache-Control": "no-store", "Vary": "Accept, Cookie",
                   "X-Content-Type-Options": "nosniff"}


class ChallengeSubmission(BaseModel):
    model_config = ConfigDict(strict=True)
    challenge_id: str = Field(min_length=1, max_length=128)
    session_id: str = Field(min_length=1, max_length=128)
    nonce: str = Field(min_length=1, max_length=128)


def create_app(settings: Settings | None = None,
               client: httpx.AsyncClient | None = None) -> FastAPI:
    settings = settings or Settings.from_env()

    @asynccontextmanager
    async def lifespan(app: FastAPI):
        if app.state.client is None:
            app.state.client = httpx.AsyncClient(timeout=settings.timeout_seconds)
        yield
        if client is None:
            await app.state.client.aclose()

    app = FastAPI(lifespan=lifespan, docs_url=None, redoc_url=None, openapi_url=None)
    app.state.settings = settings
    app.state.client = client
    app.state.challenge_store = InMemoryChallengeStore()
    app.state.session_store = InMemorySessionStore()

    def cookie(response: Response, name: str, value: str) -> None:
        response.set_cookie(name, value, httponly=True, secure=settings.cookie_secure,
                            samesite="strict", max_age=LIFETIME, path="/")

    def page(destination: str) -> Response:
        headers = {**PRIVATE_HEADERS, "Content-Security-Policy":
                   "default-src 'none'; script-src 'self'; connect-src 'self'; "
                   "base-uri 'none'; frame-ancestors 'none'; form-action 'self'"}
        return HTMLResponse(challenge_page(destination), headers=headers)

    @app.get("/health")
    async def health():
        return {"status": "ok"}

    @app.get("/challenge")
    async def show_challenge(request: Request):
        return page(request.query_params.get("next", "/"))

    @app.get("/challenge/client.js")
    async def challenge_script():
        return Response(CLIENT_SCRIPT, media_type="application/javascript", headers=PRIVATE_HEADERS)

    @app.post("/challenge")
    async def issue_challenge():
        # Identity is generated by the server, never selected by the request body.
        session_id = secrets.token_urlsafe(32)
        challenge = create_challenge(session_id=session_id, store=app.state.challenge_store)
        response = JSONResponse(challenge.to_dict(), headers=PRIVATE_HEADERS)
        cookie(response, "gateway_challenge_session", session_id)
        return response

    @app.post("/challenge/verify")
    async def verify_challenge_endpoint(request: Request, body: ChallengeSubmission):
        bound_session = request.cookies.get("gateway_challenge_session", "")
        if (not secrets.compare_digest(bound_session.encode(), body.session_id.encode())
                or not verify_challenge(body.challenge_id, bound_session, body.nonce,
                                        store=app.state.challenge_store)):
            return Response(status_code=403, headers=PRIVATE_HEADERS)
        app.state.session_store.issue(bound_session, settings.site_id, LIFETIME)
        token = create_access_token(bound_session, settings.token_secret, LIFETIME, settings.site_id)
        response = Response(content=b"challenge-valid", headers=PRIVATE_HEADERS)
        cookie(response, "gateway_session", token)
        response.delete_cookie("gateway_challenge_session", path="/",
                               secure=settings.cookie_secure, httponly=True, samesite="strict")
        return response

    @app.api_route("/{path:path}", methods=["GET", "POST", "PUT", "PATCH", "DELETE",
                                           "OPTIONS", "HEAD"])
    async def gateway(request: Request):
        request_id = str(uuid4())
        decision, reasons = evaluate_request(request, settings, app.state.session_store)
        record_decision(request_id=request_id, site_id=settings.site_id,
                        method=request.method, path=request.url.path,
                        decision=decision.value, reasons=reasons)
        if decision is Decision.CHALLENGE:
            destination = request.url.path
            if request.url.query:
                destination += "?" + request.url.query
            response = page(destination)
        elif decision is Decision.BLOCK:
            response = Response(status_code=403, headers=PRIVATE_HEADERS)
        else:
            try:
                origin = await proxy_request(app.state.client, request, settings.origin_url)
            except httpx.RequestError:
                return Response(status_code=502, headers={**PRIVATE_HEADERS,
                                                         "x-request-id": request_id})
            excluded = {"content-length", "transfer-encoding", "connection", "content-encoding",
                        "keep-alive", "proxy-authenticate", "proxy-authorization", "te",
                        "trailer", "upgrade", "set-cookie"}
            excluded.update(part.strip().lower() for part in origin.headers.get("connection", "").split(","))
            headers = {key: value for key, value in origin.headers.items() if key.lower() not in excluded}
            headers.update({"cache-control": "no-store", "vary": "Accept, Cookie"})
            response = Response(origin.content, status_code=origin.status_code, headers=headers)
            for value in origin.headers.get_list("set-cookie"):
                if not value.split("=", 1)[0].strip().lower().startswith("gateway_"):
                    response.headers.append("set-cookie", value)
        response.headers["x-request-id"] = request_id
        return response

    return app


app = create_app()
