import hmac

from gateway.detection.crawler_identity import classify_user_agent
from gateway.detection.signals import Signals
from gateway.sessions.tokens import verify_access_token


def collect_signals(request, settings, sessions, evidence):
    token = request.cookies.get("gateway_session")
    session_id = verify_access_token(token, settings.token_secret, settings.site_id,
                                     settings.token_previous_secrets) if token else None
    valid = bool(session_id and sessions.valid(session_id, settings.site_id))
    binding = request.cookies.get("gateway_challenge_session")
    evidence_id = binding if request.url.path == "/challenge/verify" else session_id or binding
    record = evidence.get(evidence_id)
    category = "api" if request.url.path.startswith("/api/") else "page"
    if record and request.url.path != "/challenge/verify":
        evidence.lifecycle(evidence_id, "protected_" + category + "_requested")
    count, previous = evidence.observe(record, category) if record else (0, None)
    record = evidence.get(evidence_id)
    interaction = evidence.interaction_signals(record) if record else {}

    mode = request.headers.get("sec-fetch-mode", "").lower()
    destination = request.headers.get("sec-fetch-dest", "").lower()
    fetch_site = request.headers.get("sec-fetch-site", "").lower()
    fetch_user = request.headers.get("sec-fetch-user", "")
    user_agent = request.headers.get("user-agent", "")
    accept = request.headers.get("accept", "").lower()
    html_navigation = request.method == "GET" and "text/html" in accept

    # Fetch Metadata is generated by browsers for top-level navigation and is much
    # more useful here than a challenge button. Client hints are deliberately NOT
    # required: browsers/privacy modes/proxies may omit them, which previously made
    # legitimate Chrome sessions intermittently receive the concealed 404 response.
    # These headers remain spoofable, so this is an access heuristic, not humanity proof.
    browser_navigation = bool(
        html_navigation
        and mode == "navigate"
        and destination == "document"
        and fetch_site in ("none", "same-origin", "same-site")
        and fetch_user == "?1"
        and "mozilla/5.0" in user_agent.lower()
    )
    inconsistent = mode == "navigate" and destination not in ("", "document", "iframe")
    development = request.headers.get("x-gateway-access-token", "")
    return Signals(
        request={"html_navigation": html_navigation,
                 "browser_navigation": browser_navigation,
                 "header_inconsistent": inconsistent, "route_category": category},
        browser=dict(record.browser) if record else {},
        behavior={"previous_category": previous,
                  "verification_ms": record.verification_ms if record else None,
                  "verification_failures": record.verification_failures if record else 0,
                  "browser_report_supplied": record.browser_report_supplied if record else False,
                  **interaction.get("behavior", {})},
        tripwires=interaction.get("tripwires", {"activated": False}),
        rate={"requests_10s": count, "burst": count > 30},
        crawler=classify_user_agent(user_agent),
        session={"id": session_id if valid else None, "valid": valid,
                 "invalid_token": bool(token and not valid),
                 "continuity": record is not None,
                 "development": bool(settings.dev_access_token and hmac.compare_digest(
                     development.encode(), settings.dev_access_token.encode()))})
